modLoader="javafml"
loaderVersion="[40,)"
license="All rights reserved"
issueTrackerURL="https://github.com/Samlegamer/Macaw-s-Bridges-Compat/issues"

[[mods]]
modId="mcwbridgesaurora"
version="1.18.2-1.3"
displayName="Macaw's Bridges - Aurora"
displayURL="https://www.curseforge.com/minecraft/mc-mods/macaws-bridges-aurora"
logoFile="logo.png"
credits=""
authors="Samlegamer"
description='''
Support :
- Bayou Blue
- Enhanced Mushrooms
'''

[[dependencies.mcwbridgesaurora]]
    modId="forge"
    mandatory=true #mandatory
    versionRange="[40,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.mcwbridgesaurora]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.2,1.19)"
    ordering="NONE"
    side="BOTH"
