modLoader="javafml"
loaderVersion="[37,)"
license="All rights reserved"
issueTrackerURL="https://github.com/Samlegamer/Macaw-s-Bridges-Compat/issues"

[[mods]]
modId="macawsbridgesbop"
version="1.17.1-1.3"
displayName="Macaw's Bridges - BOP"
displayURL="https://www.curseforge.com/minecraft/mc-mods/macaws-bridges-biome-o-plenty"
logoFile="img.png"
credits="sketch_macaw"
authors="Samlegamer"

description='''
Compatibility between Macaw's Bridges and Biome O' Plenty for Minecraft 1.17.1 !
'''

[[dependencies.macawsbridgesbop]]
    modId="forge"
    mandatory=true
    versionRange="[37,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.macawsbridgesbop]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.17.1,1.18)"
    ordering="NONE"
    side="BOTH"
