modLoader="javafml"
loaderVersion="[43,)"
license="All rights reserved"
issueTrackerURL="https://github.com/Samlegamer/Macaw-s-Bridges-Compat/issues"

[[mods]]
modId="mcwbridgesabnormals"
version="1.19.2-1.2"
displayName="Macaw's Bridges - Abnormals"
displayURL="https://www.curseforge.com/minecraft/mc-mods/macaws-bridges-abnormals"
logoFile="logo.png"
credits=""
authors="Samlegamer"
description='''
Compatibility with Abnormals Mod and Macaw's Bridges for Minecraft 1.19.2 !
Support :
- Buzzier Bees
- Atmospheric
- Autumnity
- Environmental
- Upgrade Aquatic
- Endergetic
'''

[[dependencies.mcwbridgesabnormals]]
    modId="forge"
    mandatory=true
    versionRange="[43,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.mcwbridgesabnormals]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.2,1.20)"
    ordering="NONE"
    side="BOTH"
