package fr.samlegamer.macawsbridgesbyg.block;

import net.kikoz.mcwbridges.objects.Bridge_Stairs;
import net.kikoz.mcwbridges.objects.Log_Bridge;
import net.kikoz.mcwbridges.objects.Rail_Bridge;
import net.kikoz.mcwbridges.util.BlockItemWithInfo;
import net.kikoz.mcwbridges.objects.Bridge_Block;
import net.kikoz.mcwbridges.objects.Bridge_Block_Rope;
import net.kikoz.mcwbridges.objects.Bridge_Support;
import net.minecraft.block.AbstractBlock;
import net.minecraft.block.Block;
import net.minecraft.item.BlockItem;
import net.minecraft.item.Item;
import net.minecraft.registry.Registries;
import net.minecraft.registry.Registry;
import net.minecraft.sound.BlockSoundGroup;
import net.minecraft.util.Identifier;

public class MBBYGBlocksRegistry
{
	private static final AbstractBlock.Settings WOOD = AbstractBlock.Settings.create().strength(0.5F, 2.5F).sounds(BlockSoundGroup.WOOD);
	private static final AbstractBlock.Settings RAILS = AbstractBlock.Settings.create().strength(0.5F, 2.5F).nonOpaque().sounds(BlockSoundGroup.WOOD);
	private static final AbstractBlock.Settings STONE = AbstractBlock.Settings.create().strength(3.0F, 5.0F).sounds(BlockSoundGroup.STONE);

	public static final Block aspen_log_bridge_middle = new Log_Bridge(WOOD);
	public static final Block rope_aspen_bridge = new Bridge_Block_Rope(WOOD);
	public static final Block aspen_bridge_pier = new Bridge_Support(WOOD);
	public static final Block aspen_log_bridge_stair = new Bridge_Stairs(WOOD);
	public static final Block aspen_rope_bridge_stair = new Bridge_Stairs(WOOD);
	public static final Block aspen_rail_bridge = new Rail_Bridge(RAILS);
	public static final Block baobab_log_bridge_middle = new Log_Bridge(WOOD);
	public static final Block rope_baobab_bridge = new Bridge_Block_Rope(WOOD);
	public static final Block baobab_bridge_pier = new Bridge_Support(WOOD);
	public static final Block baobab_log_bridge_stair = new Bridge_Stairs(WOOD);
	public static final Block baobab_rope_bridge_stair = new Bridge_Stairs(WOOD);
	public static final Block baobab_rail_bridge = new Rail_Bridge(RAILS);
	public static final Block blue_enchanted_log_bridge_middle = new Log_Bridge(WOOD);
	public static final Block rope_blue_enchanted_bridge = new Bridge_Block_Rope(WOOD);
	public static final Block blue_enchanted_bridge_pier = new Bridge_Support(WOOD);
	public static final Block blue_enchanted_log_bridge_stair = new Bridge_Stairs(WOOD);
	public static final Block blue_enchanted_rope_bridge_stair = new Bridge_Stairs(WOOD);
	public static final Block blue_enchanted_rail_bridge = new Rail_Bridge(RAILS);
	public static final Block cika_log_bridge_middle = new Log_Bridge(WOOD);
	public static final Block rope_cika_bridge = new Bridge_Block_Rope(WOOD);
	public static final Block cika_bridge_pier = new Bridge_Support(WOOD);
	public static final Block cika_log_bridge_stair = new Bridge_Stairs(WOOD);
	public static final Block cika_rope_bridge_stair = new Bridge_Stairs(WOOD);
	public static final Block cika_rail_bridge = new Rail_Bridge(RAILS);
	public static final Block cypress_log_bridge_middle = new Log_Bridge(WOOD);
	public static final Block rope_cypress_bridge = new Bridge_Block_Rope(WOOD);
	public static final Block cypress_bridge_pier = new Bridge_Support(WOOD);
	public static final Block cypress_log_bridge_stair = new Bridge_Stairs(WOOD);
	public static final Block cypress_rope_bridge_stair = new Bridge_Stairs(WOOD);
	public static final Block cypress_rail_bridge = new Rail_Bridge(RAILS);
	public static final Block ebony_log_bridge_middle = new Log_Bridge(WOOD);
	public static final Block rope_ebony_bridge = new Bridge_Block_Rope(WOOD);
	public static final Block ebony_bridge_pier = new Bridge_Support(WOOD);
	public static final Block ebony_log_bridge_stair = new Bridge_Stairs(WOOD);
	public static final Block ebony_rope_bridge_stair = new Bridge_Stairs(WOOD);
	public static final Block ebony_rail_bridge = new Rail_Bridge(RAILS);
	public static final Block fir_log_bridge_middle = new Log_Bridge(WOOD);
	public static final Block rope_fir_bridge = new Bridge_Block_Rope(WOOD);
	public static final Block fir_bridge_pier = new Bridge_Support(WOOD);
	public static final Block fir_log_bridge_stair = new Bridge_Stairs(WOOD);
	public static final Block fir_rope_bridge_stair = new Bridge_Stairs(WOOD);
	public static final Block fir_rail_bridge = new Rail_Bridge(RAILS);
	public static final Block green_enchanted_log_bridge_middle = new Log_Bridge(WOOD);
	public static final Block rope_green_enchanted_bridge = new Bridge_Block_Rope(WOOD);
	public static final Block green_enchanted_bridge_pier = new Bridge_Support(WOOD);
	public static final Block green_enchanted_log_bridge_stair = new Bridge_Stairs(WOOD);
	public static final Block green_enchanted_rope_bridge_stair = new Bridge_Stairs(WOOD);
	public static final Block green_enchanted_rail_bridge = new Rail_Bridge(RAILS);
	public static final Block holly_log_bridge_middle = new Log_Bridge(WOOD);
	public static final Block rope_holly_bridge = new Bridge_Block_Rope(WOOD);
	public static final Block holly_bridge_pier = new Bridge_Support(WOOD);
	public static final Block holly_log_bridge_stair = new Bridge_Stairs(WOOD);
	public static final Block holly_rope_bridge_stair = new Bridge_Stairs(WOOD);
	public static final Block holly_rail_bridge = new Rail_Bridge(RAILS);
	public static final Block ironwood_log_bridge_middle = new Log_Bridge(WOOD);
	public static final Block rope_ironwood_bridge = new Bridge_Block_Rope(WOOD);
	public static final Block ironwood_bridge_pier = new Bridge_Support(WOOD);
	public static final Block ironwood_log_bridge_stair = new Bridge_Stairs(WOOD);
	public static final Block ironwood_rope_bridge_stair = new Bridge_Stairs(WOOD);
	public static final Block ironwood_rail_bridge = new Rail_Bridge(RAILS);
	public static final Block jacaranda_log_bridge_middle = new Log_Bridge(WOOD);
	public static final Block rope_jacaranda_bridge = new Bridge_Block_Rope(WOOD);
	public static final Block jacaranda_bridge_pier = new Bridge_Support(WOOD);
	public static final Block jacaranda_log_bridge_stair = new Bridge_Stairs(WOOD);
	public static final Block jacaranda_rope_bridge_stair = new Bridge_Stairs(WOOD);
	public static final Block jacaranda_rail_bridge = new Rail_Bridge(RAILS);
	public static final Block mahogany_log_bridge_middle = new Log_Bridge(WOOD);
	public static final Block rope_mahogany_bridge = new Bridge_Block_Rope(WOOD);
	public static final Block mahogany_bridge_pier = new Bridge_Support(WOOD);
	public static final Block mahogany_log_bridge_stair = new Bridge_Stairs(WOOD);
	public static final Block mahogany_rope_bridge_stair = new Bridge_Stairs(WOOD);
	public static final Block mahogany_rail_bridge = new Rail_Bridge(RAILS);
	public static final Block maple_log_bridge_middle = new Log_Bridge(WOOD);
	public static final Block rope_maple_bridge = new Bridge_Block_Rope(WOOD);
	public static final Block maple_bridge_pier = new Bridge_Support(WOOD);
	public static final Block maple_log_bridge_stair = new Bridge_Stairs(WOOD);
	public static final Block maple_rope_bridge_stair = new Bridge_Stairs(WOOD);
	public static final Block maple_rail_bridge = new Rail_Bridge(RAILS);
	public static final Block palm_log_bridge_middle = new Log_Bridge(WOOD);
	public static final Block rope_palm_bridge = new Bridge_Block_Rope(WOOD);
	public static final Block palm_bridge_pier = new Bridge_Support(WOOD);
	public static final Block palm_log_bridge_stair = new Bridge_Stairs(WOOD);
	public static final Block palm_rope_bridge_stair = new Bridge_Stairs(WOOD);
	public static final Block palm_rail_bridge = new Rail_Bridge(RAILS);
	public static final Block pine_log_bridge_middle = new Log_Bridge(WOOD);
	public static final Block rope_pine_bridge = new Bridge_Block_Rope(WOOD);
	public static final Block pine_bridge_pier = new Bridge_Support(WOOD);
	public static final Block pine_log_bridge_stair = new Bridge_Stairs(WOOD);
	public static final Block pine_rope_bridge_stair = new Bridge_Stairs(WOOD);
	public static final Block pine_rail_bridge = new Rail_Bridge(RAILS);
	public static final Block rainbow_eucalyptus_log_bridge_middle = new Log_Bridge(WOOD);
	public static final Block rope_rainbow_eucalyptus_bridge = new Bridge_Block_Rope(WOOD);
	public static final Block rainbow_eucalyptus_bridge_pier = new Bridge_Support(WOOD);
	public static final Block rainbow_eucalyptus_log_bridge_stair = new Bridge_Stairs(WOOD);
	public static final Block rainbow_eucalyptus_rope_bridge_stair = new Bridge_Stairs(WOOD);
	public static final Block rainbow_eucalyptus_rail_bridge = new Rail_Bridge(RAILS);
	public static final Block redwood_log_bridge_middle = new Log_Bridge(WOOD);
	public static final Block rope_redwood_bridge = new Bridge_Block_Rope(WOOD);
	public static final Block redwood_bridge_pier = new Bridge_Support(WOOD);
	public static final Block redwood_log_bridge_stair = new Bridge_Stairs(WOOD);
	public static final Block redwood_rope_bridge_stair = new Bridge_Stairs(WOOD);
	public static final Block redwood_rail_bridge = new Rail_Bridge(RAILS);
	public static final Block sakura_log_bridge_middle = new Log_Bridge(WOOD);
	public static final Block rope_sakura_bridge = new Bridge_Block_Rope(WOOD);
	public static final Block sakura_bridge_pier = new Bridge_Support(WOOD);
	public static final Block sakura_log_bridge_stair = new Bridge_Stairs(WOOD);
	public static final Block sakura_rope_bridge_stair = new Bridge_Stairs(WOOD);
	public static final Block sakura_rail_bridge = new Rail_Bridge(RAILS);
	public static final Block skyris_log_bridge_middle = new Log_Bridge(WOOD);
	public static final Block rope_skyris_bridge = new Bridge_Block_Rope(WOOD);
	public static final Block skyris_bridge_pier = new Bridge_Support(WOOD);
	public static final Block skyris_log_bridge_stair = new Bridge_Stairs(WOOD);
	public static final Block skyris_rope_bridge_stair = new Bridge_Stairs(WOOD);
	public static final Block skyris_rail_bridge = new Rail_Bridge(RAILS);
	public static final Block white_mangrove_log_bridge_middle = new Log_Bridge(WOOD);
	public static final Block rope_white_mangrove_bridge = new Bridge_Block_Rope(WOOD);
	public static final Block white_mangrove_bridge_pier = new Bridge_Support(WOOD);
	public static final Block white_mangrove_log_bridge_stair = new Bridge_Stairs(WOOD);
	public static final Block white_mangrove_rope_bridge_stair = new Bridge_Stairs(WOOD);
	public static final Block white_mangrove_rail_bridge = new Rail_Bridge(RAILS);
	public static final Block willow_log_bridge_middle = new Log_Bridge(WOOD);
	public static final Block rope_willow_bridge = new Bridge_Block_Rope(WOOD);
	public static final Block willow_bridge_pier = new Bridge_Support(WOOD);
	public static final Block willow_log_bridge_stair = new Bridge_Stairs(WOOD);
	public static final Block willow_rope_bridge_stair = new Bridge_Stairs(WOOD);
	public static final Block willow_rail_bridge = new Rail_Bridge(RAILS);
	public static final Block witch_hazel_log_bridge_middle = new Log_Bridge(WOOD);
	public static final Block rope_witch_hazel_bridge = new Bridge_Block_Rope(WOOD);
	public static final Block witch_hazel_bridge_pier = new Bridge_Support(WOOD);
	public static final Block witch_hazel_log_bridge_stair = new Bridge_Stairs(WOOD);
	public static final Block witch_hazel_rope_bridge_stair = new Bridge_Stairs(WOOD);
	public static final Block witch_hazel_rail_bridge = new Rail_Bridge(RAILS);
	public static final Block zelkova_log_bridge_middle = new Log_Bridge(WOOD);
	public static final Block rope_zelkova_bridge = new Bridge_Block_Rope(WOOD);
	public static final Block zelkova_bridge_pier = new Bridge_Support(WOOD);
	public static final Block zelkova_log_bridge_stair = new Bridge_Stairs(WOOD);
	public static final Block zelkova_rope_bridge_stair = new Bridge_Stairs(WOOD);
	public static final Block zelkova_rail_bridge = new Rail_Bridge(RAILS);
	public static final Block florus_log_bridge_middle = new Log_Bridge(WOOD);
	public static final Block rope_florus_bridge = new Bridge_Block_Rope(WOOD);
	public static final Block florus_bridge_pier = new Bridge_Support(WOOD);
	public static final Block florus_log_bridge_stair = new Bridge_Stairs(WOOD);
	public static final Block florus_rope_bridge_stair = new Bridge_Stairs(WOOD);
	public static final Block florus_rail_bridge = new Rail_Bridge(RAILS);
	
	public static final Block dacite_bricks_bridge = new Bridge_Block(STONE);
	public static final Block dacite_bricks_bridge_pier = new Bridge_Support(STONE);
	public static final Block dacite_bricks_bridge_stair = new Bridge_Stairs(STONE);
	public static final Block balustrade_dacite_bricks_bridge = new Bridge_Block(STONE);
	public static final Block red_rock_bricks_bridge = new Bridge_Block(STONE);
	public static final Block red_rock_bricks_bridge_pier = new Bridge_Support(STONE);
	public static final Block red_rock_bricks_bridge_stair = new Bridge_Stairs(STONE);
	public static final Block balustrade_red_rock_bricks_bridge = new Bridge_Block(STONE);
	public static final Block pink_sandstone_bridge = new Bridge_Block(STONE);
	public static final Block pink_sandstone_bridge_pier = new Bridge_Support(STONE);
	public static final Block pink_sandstone_bridge_stair = new Bridge_Stairs(STONE);
	public static final Block balustrade_pink_sandstone_bridge = new Bridge_Block(STONE);
	public static final Block white_sandstone_bridge = new Bridge_Block(STONE);
	public static final Block white_sandstone_bridge_pier = new Bridge_Support(STONE);
	public static final Block white_sandstone_bridge_stair = new Bridge_Stairs(STONE);
	public static final Block balustrade_white_sandstone_bridge = new Bridge_Block(STONE);
	public static final Block blue_sandstone_bridge = new Bridge_Block(STONE);
	public static final Block blue_sandstone_bridge_pier = new Bridge_Support(STONE);
	public static final Block blue_sandstone_bridge_stair = new Bridge_Stairs(STONE);
	public static final Block balustrade_blue_sandstone_bridge = new Bridge_Block(STONE);
	public static final Block purple_sandstone_bridge = new Bridge_Block(STONE);
	public static final Block purple_sandstone_bridge_pier = new Bridge_Support(STONE);
	public static final Block purple_sandstone_bridge_stair = new Bridge_Stairs(STONE);
	public static final Block balustrade_purple_sandstone_bridge = new Bridge_Block(STONE);
	public static final Block black_sandstone_bridge = new Bridge_Block(STONE);
	public static final Block black_sandstone_bridge_pier = new Bridge_Support(STONE);
	public static final Block black_sandstone_bridge_stair = new Bridge_Stairs(STONE);
	public static final Block balustrade_black_sandstone_bridge = new Bridge_Block(STONE);
	public static final Block windswept_sandstone_bridge = new Bridge_Block(STONE);
	public static final Block windswept_sandstone_bridge_pier = new Bridge_Support(STONE);
	public static final Block windswept_sandstone_bridge_stair = new Bridge_Stairs(STONE);
	public static final Block balustrade_windswept_sandstone_bridge = new Bridge_Block(STONE);

	public static void registry()
	{
		add("aspen_log_bridge_middle", aspen_log_bridge_middle);
		add("rope_aspen_bridge", rope_aspen_bridge);
		add("aspen_bridge_pier", aspen_bridge_pier);
		add("aspen_log_bridge_stair", aspen_log_bridge_stair);
		add("aspen_rope_bridge_stair", aspen_rope_bridge_stair);
		add("aspen_rail_bridge", aspen_rail_bridge);
		add("baobab_log_bridge_middle", baobab_log_bridge_middle);
		add("rope_baobab_bridge", rope_baobab_bridge);
		add("baobab_bridge_pier", baobab_bridge_pier);
		add("baobab_log_bridge_stair", baobab_log_bridge_stair);
		add("baobab_rope_bridge_stair", baobab_rope_bridge_stair);
		add("baobab_rail_bridge", baobab_rail_bridge);
		add("blue_enchanted_log_bridge_middle", blue_enchanted_log_bridge_middle);
		add("rope_blue_enchanted_bridge", rope_blue_enchanted_bridge);
		add("blue_enchanted_bridge_pier", blue_enchanted_bridge_pier);
		add("blue_enchanted_log_bridge_stair", blue_enchanted_log_bridge_stair);
		add("blue_enchanted_rope_bridge_stair", blue_enchanted_rope_bridge_stair);
		add("blue_enchanted_rail_bridge", blue_enchanted_rail_bridge);
		add("cika_log_bridge_middle", cika_log_bridge_middle);
		add("rope_cika_bridge", rope_cika_bridge);
		add("cika_bridge_pier", cika_bridge_pier);
		add("cika_log_bridge_stair", cika_log_bridge_stair);
		add("cika_rope_bridge_stair", cika_rope_bridge_stair);
		add("cika_rail_bridge", cika_rail_bridge);
		add("cypress_log_bridge_middle", cypress_log_bridge_middle);
		add("rope_cypress_bridge", rope_cypress_bridge);
		add("cypress_bridge_pier", cypress_bridge_pier);
		add("cypress_log_bridge_stair", cypress_log_bridge_stair);
		add("cypress_rope_bridge_stair", cypress_rope_bridge_stair);
		add("cypress_rail_bridge", cypress_rail_bridge);
		add("ebony_log_bridge_middle", ebony_log_bridge_middle);
		add("rope_ebony_bridge", rope_ebony_bridge);
		add("ebony_bridge_pier", ebony_bridge_pier);
		add("ebony_log_bridge_stair", ebony_log_bridge_stair);
		add("ebony_rope_bridge_stair", ebony_rope_bridge_stair);
		add("ebony_rail_bridge", ebony_rail_bridge);
		add("fir_log_bridge_middle", fir_log_bridge_middle);
		add("rope_fir_bridge", rope_fir_bridge);
		add("fir_bridge_pier", fir_bridge_pier);
		add("fir_log_bridge_stair", fir_log_bridge_stair);
		add("fir_rope_bridge_stair", fir_rope_bridge_stair);
		add("fir_rail_bridge", fir_rail_bridge);
		add("green_enchanted_log_bridge_middle", green_enchanted_log_bridge_middle);
		add("rope_green_enchanted_bridge", rope_green_enchanted_bridge);
		add("green_enchanted_bridge_pier", green_enchanted_bridge_pier);
		add("green_enchanted_log_bridge_stair", green_enchanted_log_bridge_stair);
		add("green_enchanted_rope_bridge_stair", green_enchanted_rope_bridge_stair);
		add("green_enchanted_rail_bridge", green_enchanted_rail_bridge);
		add("holly_log_bridge_middle", holly_log_bridge_middle);
		add("rope_holly_bridge", rope_holly_bridge);
		add("holly_bridge_pier", holly_bridge_pier);
		add("holly_log_bridge_stair", holly_log_bridge_stair);
		add("holly_rope_bridge_stair", holly_rope_bridge_stair);
		add("holly_rail_bridge", holly_rail_bridge);
		add("ironwood_log_bridge_middle", ironwood_log_bridge_middle);
		add("rope_ironwood_bridge", rope_ironwood_bridge);
		add("ironwood_bridge_pier", ironwood_bridge_pier);
		add("ironwood_log_bridge_stair", ironwood_log_bridge_stair);
		add("ironwood_rope_bridge_stair", ironwood_rope_bridge_stair);
		add("ironwood_rail_bridge", ironwood_rail_bridge);
		add("jacaranda_log_bridge_middle", jacaranda_log_bridge_middle);
		add("rope_jacaranda_bridge", rope_jacaranda_bridge);
		add("jacaranda_bridge_pier", jacaranda_bridge_pier);
		add("jacaranda_log_bridge_stair", jacaranda_log_bridge_stair);
		add("jacaranda_rope_bridge_stair", jacaranda_rope_bridge_stair);
		add("jacaranda_rail_bridge", jacaranda_rail_bridge);
		add("mahogany_log_bridge_middle", mahogany_log_bridge_middle);
		add("rope_mahogany_bridge", rope_mahogany_bridge);
		add("mahogany_bridge_pier", mahogany_bridge_pier);
		add("mahogany_log_bridge_stair", mahogany_log_bridge_stair);
		add("mahogany_rope_bridge_stair", mahogany_rope_bridge_stair);
		add("mahogany_rail_bridge", mahogany_rail_bridge);
		add("maple_log_bridge_middle", maple_log_bridge_middle);
		add("rope_maple_bridge", rope_maple_bridge);
		add("maple_bridge_pier", maple_bridge_pier);
		add("maple_log_bridge_stair", maple_log_bridge_stair);
		add("maple_rope_bridge_stair", maple_rope_bridge_stair);
		add("maple_rail_bridge", maple_rail_bridge);
		add("palm_log_bridge_middle", palm_log_bridge_middle);
		add("rope_palm_bridge", rope_palm_bridge);
		add("palm_bridge_pier", palm_bridge_pier);
		add("palm_log_bridge_stair", palm_log_bridge_stair);
		add("palm_rope_bridge_stair", palm_rope_bridge_stair);
		add("palm_rail_bridge", palm_rail_bridge);
		add("pine_log_bridge_middle", pine_log_bridge_middle);
		add("rope_pine_bridge", rope_pine_bridge);
		add("pine_bridge_pier", pine_bridge_pier);
		add("pine_log_bridge_stair", pine_log_bridge_stair);
		add("pine_rope_bridge_stair", pine_rope_bridge_stair);
		add("pine_rail_bridge", pine_rail_bridge);
		add("rainbow_eucalyptus_log_bridge_middle", rainbow_eucalyptus_log_bridge_middle);
		add("rope_rainbow_eucalyptus_bridge", rope_rainbow_eucalyptus_bridge);
		add("rainbow_eucalyptus_bridge_pier", rainbow_eucalyptus_bridge_pier);
		add("rainbow_eucalyptus_log_bridge_stair", rainbow_eucalyptus_log_bridge_stair);
		add("rainbow_eucalyptus_rope_bridge_stair", rainbow_eucalyptus_rope_bridge_stair);
		add("rainbow_eucalyptus_rail_bridge", rainbow_eucalyptus_rail_bridge);
		add("redwood_log_bridge_middle", redwood_log_bridge_middle);
		add("rope_redwood_bridge", rope_redwood_bridge);
		add("redwood_bridge_pier", redwood_bridge_pier);
		add("redwood_log_bridge_stair", redwood_log_bridge_stair);
		add("redwood_rope_bridge_stair", redwood_rope_bridge_stair);
		add("redwood_rail_bridge", redwood_rail_bridge);
		add("sakura_log_bridge_middle", sakura_log_bridge_middle);
		add("rope_sakura_bridge", rope_sakura_bridge);
		add("sakura_bridge_pier", sakura_bridge_pier);
		add("sakura_log_bridge_stair", sakura_log_bridge_stair);
		add("sakura_rope_bridge_stair", sakura_rope_bridge_stair);
		add("sakura_rail_bridge", sakura_rail_bridge);
		add("skyris_log_bridge_middle", skyris_log_bridge_middle);
		add("rope_skyris_bridge", rope_skyris_bridge);
		add("skyris_bridge_pier", skyris_bridge_pier);
		add("skyris_log_bridge_stair", skyris_log_bridge_stair);
		add("skyris_rope_bridge_stair", skyris_rope_bridge_stair);
		add("skyris_rail_bridge", skyris_rail_bridge);
		add("white_mangrove_log_bridge_middle", white_mangrove_log_bridge_middle);
		add("rope_white_mangrove_bridge", rope_white_mangrove_bridge);
		add("white_mangrove_bridge_pier", white_mangrove_bridge_pier);
		add("white_mangrove_log_bridge_stair", white_mangrove_log_bridge_stair);
		add("white_mangrove_rope_bridge_stair", white_mangrove_rope_bridge_stair);
		add("white_mangrove_rail_bridge", white_mangrove_rail_bridge);
		add("willow_log_bridge_middle", willow_log_bridge_middle);
		add("rope_willow_bridge", rope_willow_bridge);
		add("willow_bridge_pier", willow_bridge_pier);
		add("willow_log_bridge_stair", willow_log_bridge_stair);
		add("willow_rope_bridge_stair", willow_rope_bridge_stair);
		add("willow_rail_bridge", willow_rail_bridge);
		add("witch_hazel_log_bridge_middle", witch_hazel_log_bridge_middle);
		add("rope_witch_hazel_bridge", rope_witch_hazel_bridge);
		add("witch_hazel_bridge_pier", witch_hazel_bridge_pier);
		add("witch_hazel_log_bridge_stair", witch_hazel_log_bridge_stair);
		add("witch_hazel_rope_bridge_stair", witch_hazel_rope_bridge_stair);
		add("witch_hazel_rail_bridge", witch_hazel_rail_bridge);
		add("zelkova_log_bridge_middle", zelkova_log_bridge_middle);
		add("rope_zelkova_bridge", rope_zelkova_bridge);
		add("zelkova_bridge_pier", zelkova_bridge_pier);
		add("zelkova_log_bridge_stair", zelkova_log_bridge_stair);
		add("zelkova_rope_bridge_stair", zelkova_rope_bridge_stair);
		add("zelkova_rail_bridge", zelkova_rail_bridge);
		add("florus_log_bridge_middle", florus_log_bridge_middle);
		add("rope_florus_bridge", rope_florus_bridge);
		add("florus_bridge_pier", florus_bridge_pier);
		add("florus_log_bridge_stair", florus_log_bridge_stair);
		add("florus_rope_bridge_stair", florus_rope_bridge_stair);
		add("florus_rail_bridge", florus_rail_bridge);
		
		add("dacite_bricks_bridge", dacite_bricks_bridge);
		add("dacite_bricks_bridge_pier", dacite_bricks_bridge_pier);
		add("dacite_bricks_bridge_stair", dacite_bricks_bridge_stair);
		add("balustrade_dacite_bricks_bridge", balustrade_dacite_bricks_bridge);
		add("red_rock_bricks_bridge", red_rock_bricks_bridge);
		add("red_rock_bricks_bridge_pier", red_rock_bricks_bridge_pier);
		add("red_rock_bricks_bridge_stair", red_rock_bricks_bridge_stair);
		add("balustrade_red_rock_bricks_bridge", balustrade_red_rock_bricks_bridge);
		add("pink_sandstone_bridge", pink_sandstone_bridge);
		add("pink_sandstone_bridge_pier", pink_sandstone_bridge_pier);
		add("pink_sandstone_bridge_stair", pink_sandstone_bridge_stair);
		add("balustrade_pink_sandstone_bridge", balustrade_pink_sandstone_bridge);
		add("white_sandstone_bridge", white_sandstone_bridge);
		add("white_sandstone_bridge_pier", white_sandstone_bridge_pier);
		add("white_sandstone_bridge_stair", white_sandstone_bridge_stair);
		add("balustrade_white_sandstone_bridge", balustrade_white_sandstone_bridge);
		add("blue_sandstone_bridge", blue_sandstone_bridge);
		add("blue_sandstone_bridge_pier", blue_sandstone_bridge_pier);
		add("blue_sandstone_bridge_stair", blue_sandstone_bridge_stair);
		add("balustrade_blue_sandstone_bridge", balustrade_blue_sandstone_bridge);
		add("purple_sandstone_bridge", purple_sandstone_bridge);
		add("purple_sandstone_bridge_pier", purple_sandstone_bridge_pier);
		add("purple_sandstone_bridge_stair", purple_sandstone_bridge_stair);
		add("balustrade_purple_sandstone_bridge", balustrade_purple_sandstone_bridge);
		add("black_sandstone_bridge", black_sandstone_bridge);
		add("black_sandstone_bridge_pier", black_sandstone_bridge_pier);
		add("black_sandstone_bridge_stair", black_sandstone_bridge_stair);
		add("balustrade_black_sandstone_bridge", balustrade_black_sandstone_bridge);
		add("windswept_sandstone_bridge", windswept_sandstone_bridge);
		add("windswept_sandstone_bridge_pier", windswept_sandstone_bridge_pier);
		add("windswept_sandstone_bridge_stair", windswept_sandstone_bridge_stair);
		add("balustrade_windswept_sandstone_bridge", balustrade_windswept_sandstone_bridge);
	}
	
	private static void add(String name, Block b)
    {
    	Registry.register(Registries.BLOCK, new Identifier("macawsbridgesbyg", name), b);
    	blockItem(b, name);
	}
    
    private static void blockItem(Block b, String name)
    {
    	if(name.contains("log_bridge_middle") || name.startsWith("rope_") || name.endsWith("_bridge"))
	    {
	        Registry.register(Registries.ITEM, new Identifier("macawsbridgesbyg", name), new BlockItemWithInfo(b, new Item.Settings()));
	    }
	    else {
	        Registry.register(Registries.ITEM, new Identifier("macawsbridgesbyg", name), new BlockItem(b, new Item.Settings()));
	    }
    }
}