modLoader="javafml"
loaderVersion="[36,)"
license="All rights reserved"
issueTrackerURL="https://github.com/Samlegamer/Macaw-s-Bridges-Compat/issues"

[[mods]]
modId="mcwbridgesaurora"
version="1.16.5-1.2"
displayName="Macaw's Bridges - Aurora"
displayURL="https://www.curseforge.com/minecraft/mc-mods/macaws-bridges-aurora"
logoFile="logo.png"
credits=""
authors="Samlegamer"
description='''
Support :
- Bayou Blue
- Enhanced Mushrooms
'''

[[dependencies.mcwbridgesaurora]]
    modId="forge"
    mandatory=true
    versionRange="[36,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.mcwbridgesaurora]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5,1.17)"
    ordering="NONE"
    side="BOTH"