modLoader="javafml"
loaderVersion="[41,)"
license="All rights reserved"
issueTrackerURL="https://github.com/Samlegamer/Macaw-s-Bridges-Compat/issues"

[[mods]]
modId="macawsbridgesbop"
version="1.19-1.5"
displayName="Macaw's Bridges - BOP"
displayURL="https://www.curseforge.com/minecraft/mc-mods/macaws-bridges-biome-o-plenty"
logoFile="img.png"
credits="sketch_macaw"
authors="Samlegamer"
displayTest="MATCH_VERSION"
description='''
Compatibility between Macaw's Bridges and Biome O' Plenty for Minecraft 1.19 !
'''
[[dependencies.macawsbridgesbop]]
    modId="forge"
    mandatory=true
    versionRange="[41,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.macawsbridgesbop]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19,1.20)"
    ordering="NONE"
    side="BOTH"

[[dependencies.macawsbridgesbop]]
    modId = "mcwbridges"
    mandatory = false
    ordering = "AFTER"
    versionRange = "NONE"

[[dependencies.macawsbridgesbop]]
    modId = "biomesoplenty"
    mandatory = false
    ordering = "AFTER"
    versionRange = "NONE"

[[dependencies.macawsbridgesbop]]
    modId = "terrablender"
    mandatory = false
    ordering = "AFTER"
    versionRange = "NONE"