modLoader="javafml"
loaderVersion="[36,)"
license="All rights reserved"
issueTrackerURL="https://github.com/Samlegamer/Macaw-s-Bridges-Compat/issues"

[[mods]]
modId="mcwbridgesmoddinglegacy"
version="1.16.5-1.0"
displayName="Macaw's Bridges - Modding Legacy"
displayURL="https://www.curseforge.com/minecraft/mc-mods/macaws-bridges-modding-legacy"
logoFile="logo.png"
credits=""
authors="Samlegamer"
description='''
Support :
- Blue Skies
- Premium Wood
'''

[[dependencies.mcwbridgesmoddinglegacy]]
    modId="forge"
    mandatory=true
    versionRange="[36,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.mcwbridgesmoddinglegacy]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5,1.17)"
    ordering="NONE"
    side="BOTH"
