modLoader="javafml"
loaderVersion="[44,)"
license="All rights reserved"
issueTrackerURL="https://github.com/Samlegamer/Macaw-s-Bridges-Compat/issues"

[[mods]]
modId="macawsbridgesbop"
version="1.19.3-1.4"
displayName="Macaw's Bridges - BOP"
displayURL="https://www.curseforge.com/minecraft/mc-mods/macaws-bridges-biome-o-plenty"
logoFile="img.png"
credits="sketch_macaw"
authors="Samlegamer"
#displayTest="MATCH_VERSION"
description='''
Compatibility Biome O' Plenty with Macaw's Bridges for Minecraft 1.19.3 !
'''

[[dependencies.macawsbridgesbop]]
    modId="forge"
    mandatory=true
    versionRange="[44,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.macawsbridgesbop]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.3,1.20)"
    ordering="NONE"
    side="BOTH"