modLoader="javafml"
loaderVersion="[40,)"
license="All rights reserved"
issueTrackerURL="https://github.com/Samlegamer/Macaw-s-Bridges-Compat/issues"

[[mods]] #mandatory
modId="macawsbridgesbop"
version="1.18.2-1.6"
displayName="Macaw's Bridges - BOP"
displayURL="https://www.curseforge.com/minecraft/mc-mods/macaws-bridges-biome-o-plenty"
logoFile="img.png"
credits="sketch_macaw"
authors="Samlegamer"

description='''
Compatibility Biome O' Plenty with Macaw's Bridges for Minecraft 1.18.2.
'''

[[dependencies.macawsbridgesbop]]
    modId="forge"
    mandatory=true
    versionRange="[40,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.macawsbridgesbop]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.2,1.19)"
    ordering="NONE"
    side="BOTH"