modLoader="javafml"
loaderVersion="[41,)"
license="All rights reserved"
issueTrackerURL="https://github.com/Samlegamer/Macaw-s-Bridges-Compat/issues"

[[mods]]
modId="mcwbridgesabnormals"
version="1.19-1.0"
displayName="Macaw's Bridges - Abnormals"
displayURL="https://www.curseforge.com/minecraft/mc-mods/macaws-bridges-abnormals"
logoFile="logo.png"
credits="sketch_macaw"
authors="Samlegamer"
displayTest="MATCH_VERSION"
description='''
Compatibility between Macaw's Bridges and Abnormals Mods for Minecraft 1.19 !

Support :
- Buzzier Bees
- Atmospheric
- Autumnity
- Environmental
- Upgrade Aquatic
- Endergetic
'''
[[dependencies.mcwbridgesabnormals]]
    modId="forge"
    mandatory=true
    versionRange="[41,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.mcwbridgesabnormals]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19,1.20)"
    ordering="NONE"
    side="BOTH"

[[dependencies.mcwbridgesabnormals]]
    modId = "mcwbridges"
    mandatory = false
    ordering = "AFTER"
    versionRange = "NONE"